spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/auto
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true